spring:
    application:
        name: notification-service
    
    data:
        mongodb:
            uri: mongodb://${MONGODB_HOST_ADDRESS:localhost}:27017
            database: ${MONGODB_NS_DATABASE:notification-service}
    
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: paymentGroup, orderGroup
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.json.trusted.packages: '*'
                spring.json.type.mapping: orderConfirmationDTO:com.example.ecommerce.notification_service.models.OrderConfirmationDTO, paymentConfirmationDTO:com.example.ecommerce.notification_service.models.PaymentConfirmationDTO
    
    mail:
        host: localhost
        port: 2025
        properties:
            mail:
                smtp:
                    trust: "*"
                auth: true
                starttls:
                    enable: true
                connectiontimeout: 5000
                timeout: 5000
                writetimeout: 5000
    
    # temporary
    cloud:
        config:
            enabled: false

# temporary
eureka:
    client:
        enabled: false

server:
    port: 8085
