services:
    ms-db-mysql-product:
        container_name: ms-db-mysql-product
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: productdb
            MYSQL_USER: productadmin
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data-product:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - microservices-net
        restart: unless-stopped
    
    ms-db-mysql-order:
        container_name: ms-db-mysql-order
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: orderdb
            MYSQL_USER: orderadmin
            MYSQL_PASSWORD: password
        volumes:
            - mysql-data-order:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - microservices-net
        restart: unless-stopped
    
    ms-db-mongodb:
        container_name: ms-db-mongodb
        image: mongo:latest
        volumes:
            - mongo-data:/data/db
        ports:
            - "27017:27017"
        networks:
            - microservices-net
        restart: unless-stopped
    
    mail-dev:
        container_name: ms-mail-dev
        image: maildev/maildev:latest
        volumes:
            - maildev-data:/data
        ports:
            - "1080:1080"
            - "1025:1025"


networks:
    microservices-net:
        driver: bridge
volumes:
    mysql-data-product:
    mysql-data-order:
    mongo-data:
    maildev-data: