services:
    ms-db-mysqldb:
        container_name: ms-db-mysql
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: productdb
            MYSQL_USER: productadmin
            MYSQL_PASSWORD: password
        #           MYSQL_DATABASE2: productdb2
        #           MYSQL_USER2: productadmin
        #           MYSQL_PASSWORD2: password
        #           and so on...
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - microservices-net
        restart: unless-stopped
    
    mail-dev:
        container_name: ms-mail-dev
        image: maildev/maildev:latest
        ports:
            - "1080:1080"
            - "1025:1025"


networks:
    microservices-net:
        driver: bridge
volumes:
    mysql-data: