# Configuration for the Spring application named "payment-service".
spring:
    application:
        # Specifies the name of the application.
        name: payment-service
    config:
        # Imports configuration from a Config Server running at localhost:8086.
        # The "optional" prefix indicates that the application will not fail to start
        # if the Config Server is unavailable.
        import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8086}
        