apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        app: ms-keycloak
    name: ms-keycloak
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ms-keycloak
    strategy: { }
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: ms-keycloak
        spec:
            containers:
                -   image: keycloak/keycloak:latest
                    name: keycloak
                    resources: { }
status: { }
