apiVersion: v1
kind: Service
metadata:
    creationTimestamp: null
    labels:
        app: ms-db-mongo
    name: ms-db-mongo
spec:
    ports:
        -   name: 27017-27017
            port: 27017
            protocol: TCP
            targetPort: 27017
    selector:
        app: ms-db-mongo
    type: ClusterIP
status:
    loadBalancer: { }
