apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        app: ms-db-mysql-payment
    name: ms-db-mysql-payment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ms-db-mysql-payment
    strategy: { }
    template:
        metadata:
            creationTimestamp: null
            labels:
                app: ms-db-mysql-payment
        spec:
            containers:
                -   image: mysql:latest
                    name: mysql
                    resources: { }
                    env:
                        -   name: MYSQL_ROOT_PASSWORD
                            value: password
                        -   name: MYSQL_DATABASE
                            value: paymentdb
                        -   name: MYSQL_USER
                            value: paymentadmin
                        -   name: MYSQL_PASSWORD
                            value: password
                        -   name: MYSQL_TCP_PORT
                            value: "3308"

status: { }
