# Configuration file for the Order Service application.

spring:
    application:
        # Specifies the name of the Spring application.
        name: order-service
    config:
        # Imports configuration from a Config Server running at the specified URL.
        # The 'optional' prefix indicates that the application can start even if the Config Server is unavailable.
        import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8086}
        