name:
    value: sampleconfigserver

spring:
    cloud:
        config:
            override-system-properties: false

# for eureka client
eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka


# for tracing