# This is the configuration file for the Spring Boot application.
# It defines application-specific properties, cloud configuration settings and
#   its configs gets associated with each microservice.
# Eureka client settings, and tracing configurations.

#name:
#    # Specifies the name of the configuration server.
#    value: sampleconfigserver

spring:
    cloud:
        config:
            # Determines whether system properties should override configuration properties.
            override-system-properties: false

# Configuration for the Eureka client.
eureka:
    instance:
        # The hostname of the Eureka instance.
        hostname: ${EUREKA_SERVER_HOST:localhost}
        prefer-ip-address: true
    client:
        service-url:
            # The default Eureka server URL for service registration and discovery.
            defaultZone: http://${eureka.instance.hostname}:8761/eureka
        register-with-eureka: true
        fetch-registry: true

# Configuration for distributed tracing.
management:
    tracing:
        sampling:
            # Sets the probability for tracing sampling. A value of 1.0 means 100% of requests are traced.
            probability: 1.0
        enabled: true
    zipkin:
        tracing:
            endpoint:
                # The endpoint for the Zipkin server.
                base-url: http://${ZIPKIN_HOST:ms-zipkin-server}:9411/api/v2/spans