# This is the configuration file for the Spring Boot application.
# It defines application-specific properties, cloud configuration settings and
#   its configs gets associated with each microservice.
# Eureka client settings, and tracing configurations.

#name:
#    # Specifies the name of the configuration server.
#    value: sampleconfigserver

spring:
    cloud:
        config:
            # Determines whether system properties should override configuration properties.
            override-system-properties: false
    
    zipkin:
        # The base URL for the Zipkin server.
        base-url: http://${ZIPKIN_BASE_URL:http://localhost:9411}
    sleuth:
        zipkin:
            # The base URL for the Zipkin server.
            base-url: http://${ZIPKIN_BASE_URL:http://localhost:9411}
        sampler:
            # The sampling probability for tracing. A value of 1.0 means 100% of requests are traced.
            probability: 1.0

# Configuration for the Eureka client.
eureka:
    instance:
        # The hostname of the Eureka instance.
        hostname: ${EUREKA_SERVER_HOST:localhost}
    client:
        service-url:
            # The default Eureka server URL for service registration and discovery.
            defaultZone: http://${EUREKA_SERVER_HOST:eureka.instance.hostname}:8761/eureka

# Configuration for distributed tracing.
management:
    tracing:
        sampling:
            # Sets the probability for tracing sampling. A value of 1.0 means 100% of requests are traced.
            probability: 1.0
    zipkin:
        tracing:
            endpoint:
                # The endpoint for the Zipkin server.
                base-url: http://${ZIPKIN_BASE_URL:http://localhost:9411}