# This is the configuration file for the Spring Boot application `customer-service`.
# It defines MongoDB connection settings and the server port configuration.

spring:
    data:
        mongodb:
            # The URI for connecting to the MongoDB database.
            # Defaults to `localhost` on port `27017` if `MONGODB_HOST_ADDRESS` is not set.
            uri: mongodb://${MONGODB_HOST_ADDRESS}:27017
            # The name of the MongoDB database to use.
            # Defaults to `customer-service` if `MONGODB_CS_DATABASE` is not set.
            database: ${MONGODB_CS_DATABASE:customer-service}

server:
    # The port on which the application will run.
    port: 8081
