# This is the configuration file for the Spring Boot application `order-service`.
# It defines JPA and Hibernate settings, MySQL database connection properties,
# Kafka producer configurations, server port, and application-specific configurations.

spring:
    jpa:
        hibernate:
            # Specifies the strategy for schema generation.
            # `update` ensures the schema is updated without dropping existing data.
            ddl-auto: update
        # Specifies the database type used by the application.
        database: mysql
    datasource:
        # The JDBC URL for connecting to the MySQL database.
        # Defaults to `localhost` on port `3307` with the database name `orderdb` if environment variables are not set.
        url: jdbc:mysql://${OS_HOST_ADDRESS}:${OS_HOST_PORT:3307}/${OS_DB:orderdb}
        # The username for the MySQL database connection.
        username: ${OS_DB_USER:orderadmin}
        # The password for the MySQL database connection.
        password: ${OS_DB_PASS:password}
        # The fully qualified name of the MySQL JDBC driver class.
        driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
        producer:
            # The Kafka bootstrap servers for connecting to the Kafka cluster.
            bootstrap-servers: ${OS_KAFKA_HOST}:${OS_KAFKA_PORT}
            # The class used to serialize the key of Kafka messages.
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            # The class used to serialize the value of Kafka messages.
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                # Maps specific JSON types to Java classes for serialization.
                spring.json.type.mapping: orderConfirmationDTO:com.example.ecommerce.order_service.models.OrderConfirmationDTO

server:
    # The port on which the application will run.
    port: 8083

application:
    config:
        # URIs for other services, used for inter-service communication.
        # Note: These URIs are placeholders and should be replaced with actual service URLs in a production environment.
        
        # The URL for the `customer-service` through the gateway service.
        customer-url: http://${GS_HOST}:8008/api/v1/customers
        # The URL for the `product-service` through the gateway service.
        product-url: http://${GS_HOST}:8008/api/v1/products
        # The URL for the `payment-service` through the gateway service.
        payment-url: http://${GS_HOST}:8008/api/v1/payments

## Configuration for distributed tracing.
#management:
#    tracing:
#        sampling:
#            # Sets the probability for tracing sampling. A value of 1.0 means 100% of requests are traced.
#            probability: 1.0
#        enabled: true
#    zipkin:
#        tracing:
#            endpoint:
#                # The endpoint for the Zipkin server.
#                base-url: ${ZIPKIN_HOST}