spring:
    jpa:
        hibernate:
            ddl-auto: update
        database: mysql
    datasource:
        url: jdbc:mysql://${OS_HOST_ADDRESS:localhost}:${OS_HOST_PORT:3307}/${OS_DB:orderdb}
        username: ${OS_DB_USER:orderadmin}
        password: ${OS_DB_PASS:password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
        producer:
            bootstrap-servers: ${OS_KAFKA_HOST:localhost}:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: orderConfirmationDTO:com.example.ecommerce.order_service.models.OrderConfirmationDTO

server:
    port: 8083

application:
    config:
        # URIs for other services, used for inter-service communication
        # Note: These URIs are placeholders and should be replaced with actual service URLs in a production environment.
        
        # redirecting towards the gateway service
        customer-url: http://localhost:8080/api/v1/customers
        product-url: http://localhost:8080/api/v1/products
        payment-url: http://localhost:8080/api/v1/payments