# This is the configuration file for the Spring Boot application `product-service`.
# It defines JPA and Hibernate settings, MySQL database connection properties,
# Flyway migration configurations, and the server port configuration.

spring:
    jpa:
        hibernate:
            # Specifies the strategy for schema validation.
            # `validate` ensures the schema matches the entity definitions without modifying the database.
            ddl-auto: validate
    datasource:
        # The JDBC URL for connecting to the MySQL database.
        # Defaults to `localhost` on port `3306` with the database name `productdb` if environment variables are not set.
        url: jdbc:mysql://${PS_HOST_ADDRESS:localhost}:${PS_HOST_PORT:3306}/${PS_DB:productdb}
        # The username for the MySQL database connection.
        username: ${PS_DB_USER:productadmin}
        # The password for the MySQL database connection.
        password: ${PS_DB_PASS:password}
        # The fully qualified name of the MySQL JDBC driver class.
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
        # Enables Flyway database migration.
        enabled: true
        # Ensures Flyway creates a baseline version when migrating a non-empty database.
        baseline-on-migrate: true
        # Sets the baseline version for Flyway migrations.
        baseline-version: 0
        # Provides a description for the baseline version.
        baseline-description: "baseline-initial"
        # Uses the same username as the datasource for Flyway migrations.
        user: ${spring.datasource.username}
        # Uses the same password as the datasource for Flyway migrations.
        password: ${spring.datasource.password}

server:
    # The port on which the application will run.
    port: 8082