spring:
    application:
        name: customer-service
    
    # temporary
    cloud:
        config:
            enabled: false
    
    data:
        mongodb:
            uri: mongodb://${MONGODB_HOST_ADDRESS:localhost}:27017
            database: ${MONGODB_CS_DATABASE:customer-service}

server:
    port: 8081

# temporary
eureka:
    client:
        enabled: false
      