# This is the configuration file for the Spring Boot application `config-discovery-service`.
# It defines the application's name and specifies the configuration server to be used.

spring:
    application:
        # The name of the Spring Boot application.
        name: config-discovery-service
    
    config:
        # Specifies the configuration server to import properties from.
        # The `optional` prefix indicates that the application will not fail to start
        # if the configuration server is unavailable.
        import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8086}